//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.10 at 09:19:13 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "soap.app/zaduzenje_mt900", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package app.soap.zaduzenje_mt900;
