//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 11:27:01 PM CEST 
//


package app.soap.izvod;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import app.model.Faktura;

import com.fasterxml.jackson.annotation.JsonBackReference;


/**
 * <p>Java class for zaglavlje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zaglavlje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="brojracuna" type="{soap.app/izvod}TBroj_racuna"/>
 *         &lt;element name="datum-naloga" type="{soap.app/izvod}TDate"/>
 *         &lt;element name="broj-preseka">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="10"/>
 *               &lt;maxInclusive value="99"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="prethodno-stanje" type="{soap.app/izvod}TStanje"/>
 *         &lt;element name="broj-promena-u-korist">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ukupno-u-korist" type="{soap.app/izvod}TStanje"/>
 *         &lt;element name="broj-promena-na-teret">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ukupno-na-teret" type="{soap.app/izvod}TStanje"/>
 *         &lt;element name="novo-stanje" type="{soap.app/izvod}TStanje"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zaglavlje", propOrder = {

})
@Entity
@Table(name="zaglavlje")
public class Zaglavlje {
	

	@Id
    @Column
    @XmlElement(name = "id_zaglavlja", required = true)
    protected String idZaglavlja;
	@XmlElement(required = true)
    protected String brojracuna;
	@Column
    @XmlElement(name = "datum-naloga", required = true)
    protected String datumNaloga;
	@Column
    @XmlElement(name = "broj-preseka")
    protected int brojPreseka;
	@Column
    @XmlElement(name = "prethodno-stanje", required = true)
    protected BigDecimal prethodnoStanje;
	@Column
    @XmlElement(name = "broj-promena-u-korist")
    protected int brojPromenaUKorist;
	@Column
    @XmlElement(name = "ukupno-u-korist", required = true)
    protected BigDecimal ukupnoUKorist;
	@Column
    @XmlElement(name = "broj-promena-na-teret")
    protected int brojPromenaNaTeret;
	@Column
    @XmlElement(name = "ukupno-na-teret", required = true)
    protected BigDecimal ukupnoNaTeret;
	@Column
    @XmlElement(name = "novo-stanje", required = true)
    protected BigDecimal novoStanje;
	
	@OneToOne(fetch = FetchType.LAZY)
	@XmlTransient
	@JoinColumn(name= "izvod", referencedColumnName = "idPoruke")
	private Izvod izvod;

    /**
     * Gets the value of the brojracuna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojracuna() {
        return brojracuna;
    }

    /**
     * Sets the value of the brojracuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojracuna(String value) {
        this.brojracuna = value;
    }

    /**
     * Gets the value of the datumNaloga property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumNaloga() {
        return datumNaloga;
    }

    /**
     * Sets the value of the datumNaloga property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumNaloga(String value) {
        this.datumNaloga = value;
    }

    /**
     * Gets the value of the brojPreseka property.
     * 
     */
    public int getBrojPreseka() {
        return brojPreseka;
    }

    /**
     * Sets the value of the brojPreseka property.
     * 
     */
    public void setBrojPreseka(int value) {
        this.brojPreseka = value;
    }

    /**
     * Gets the value of the prethodnoStanje property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrethodnoStanje() {
        return prethodnoStanje;
    }

    /**
     * Sets the value of the prethodnoStanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrethodnoStanje(BigDecimal value) {
        this.prethodnoStanje = value;
    }

    /**
     * Gets the value of the brojPromenaUKorist property.
     * 
     */
    public int getBrojPromenaUKorist() {
        return brojPromenaUKorist;
    }

    /**
     * Sets the value of the brojPromenaUKorist property.
     * 
     */
    public void setBrojPromenaUKorist(int value) {
        this.brojPromenaUKorist = value;
    }

    /**
     * Gets the value of the ukupnoUKorist property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupnoUKorist() {
        return ukupnoUKorist;
    }

    /**
     * Sets the value of the ukupnoUKorist property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupnoUKorist(BigDecimal value) {
        this.ukupnoUKorist = value;
    }

    /**
     * Gets the value of the brojPromenaNaTeret property.
     * 
     */
    public int getBrojPromenaNaTeret() {
        return brojPromenaNaTeret;
    }

    /**
     * Sets the value of the brojPromenaNaTeret property.
     * 
     */
    public void setBrojPromenaNaTeret(int value) {
        this.brojPromenaNaTeret = value;
    }

    /**
     * Gets the value of the ukupnoNaTeret property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupnoNaTeret() {
        return ukupnoNaTeret;
    }

    /**
     * Sets the value of the ukupnoNaTeret property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupnoNaTeret(BigDecimal value) {
        this.ukupnoNaTeret = value;
    }

    /**
     * Gets the value of the novoStanje property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNovoStanje() {
        return novoStanje;
    }

    /**
     * Sets the value of the novoStanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNovoStanje(BigDecimal value) {
        this.novoStanje = value;
    }
   

	public Izvod getIzvod() {
		return izvod;
	}

	public void setIzvod(Izvod izvod) {
		this.izvod = izvod;
	}
	
	public String getIdZaglavlja() {
		return idZaglavlja;
	}

	public void setIdZaglavlja(String idZaglavlja) {
		this.idZaglavlja = idZaglavlja;
	}

}
