//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 11:46:05 PM CEST 
//


package app.soap.clearing_mt102;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clearing_mt102 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="clearing_mt102">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id_poruke">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="swift_kod_banke_duznika">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[A-Z]{6}[A-Z0-9]{2}(X{3}|[A-Z0-9]{3})?"/>
 *               &lt;minLength value="8"/>
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="obracunski_racun_banke_duznika">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{3}-[0-9]{13}-[0-9]{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="swift_kod_banke_poverioca">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[A-Z]{6}[A-Z0-9]{2}(X{3}|[A-Z0-9]{3})?"/>
 *               &lt;minLength value="8"/>
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="obracunski_racun_banke_poverioca">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{3}-[0-9]{13}-[0-9]{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ukupan_iznos">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="2"/>
 *               &lt;totalDigits value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sifra_valute">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datum_valute">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}-[0-9]{2}-[0-9]{4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datum">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}-[0-9]{2}-[0-9]{4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PojedinacnoPlacanje">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="id_naloga_za_placanje">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="50"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="duznik_nalogodavac">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="svrha_placanja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="primalac-poverilac">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="datum_naloga">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0-9]{2}-[0-9]{2}-[0-9]{4}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="datum_valute_p">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0-9]{2}-[0-9]{2}-[0-9]{4}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="broj_racuna_duznika">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0-9]{3}-[0-9]{13}-[0-9]{2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="model_zaduzenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;minInclusive value="10"/>
 *                         &lt;maxInclusive value="99"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="poziv_na_broj_zaduzenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;totalDigits value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="broj_racuna_poverioca">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0-9]{3}-[0-9]{13}-[0-9]{2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="model_odobrenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;minInclusive value="10"/>
 *                         &lt;maxInclusive value="99"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="poziv_na_broj_odobrenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;totalDigits value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="iznos">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;fractionDigits value="2"/>
 *                         &lt;totalDigits value="15"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="sifra_valute_p">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clearing_mt102", propOrder = {
    "idPoruke",
    "swiftKodBankeDuznika",
    "obracunskiRacunBankeDuznika",
    "swiftKodBankePoverioca",
    "obracunskiRacunBankePoverioca",
    "ukupanIznos",
    "sifraValute",
    "datumValute",
    "datum",
    "pojedinacnoPlacanje"
})
@Entity
@Table(name="clearing_mt102")
public class ClearingMt102 {
    @Id
    @Column
    @XmlElement(name = "id_poruke", required = true)
   // @GeneratedValue(strategy=GenerationType.IDENTITY)
    protected String idPoruke;
    @Column
    @XmlElement(name = "swift_kod_banke_duznika", required = true)
    protected String swiftKodBankeDuznika;
    @Column
    @XmlElement(name = "obracunski_racun_banke_duznika", required = true, defaultValue = "000-0000000000000-00")
    protected String obracunskiRacunBankeDuznika;
    @Column
    @XmlElement(name = "swift_kod_banke_poverioca", required = true)
    protected String swiftKodBankePoverioca;
    @Column
    @XmlElement(name = "obracunski_racun_banke_poverioca", required = true, defaultValue = "000-0000000000000-00")
    protected String obracunskiRacunBankePoverioca;
    @Column
    @XmlElement(name = "ukupan_iznos", required = true)
    protected BigDecimal ukupanIznos;
    @Column
    @XmlElement(name = "sifra_valute", required = true)
    protected String sifraValute;
    @Column
    @XmlElement(name = "datum_valute", required = true, defaultValue = "00-00-0000")
    protected String datumValute;
    @Column
    @XmlElement(required = true, defaultValue = "00-00-0000")
    protected String datum;
    
  //  @Column
  //  @ElementCollection(targetClass=PojedinacnoPlacanje.class)
  //  protected List<PojedinacnoPlacanje> pojedinacnoPlacanje;
    
 //   @ManyToOne
 //   @JoinColumn(name = "pojedinacno_id")

   // @OneToMany
  //	@JoinTable(name = "clearing_mt102_pojedinacno", joinColumns = @JoinColumn(name = "id_poruke"), inverseJoinColumns = @JoinColumn(name = "id_naloga_za_placanje"))
  //  @XmlElement(required = true)
    @XmlElement(name ="pojedinacnoPlacanje")
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy = "matClearing")
    protected Set<PojedinacnoPlacanje> pojedinacnoPlacanje = new HashSet<PojedinacnoPlacanje>();
    /*
    public List<PojedinacnoPlacanje> getPojedinacnoPlacanjeList() {
        if (pojedinacnoPlacanje == null) {
            pojedinacnoPlacanje = new ArrayList<PojedinacnoPlacanje>();
        }
        return this.pojedinacnoPlacanje;
    }
    */
    /**
     * Gets the value of the idPoruke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPoruke() {
        return idPoruke;
    }

    /**
     * Sets the value of the idPoruke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPoruke(String value) {
        this.idPoruke = value;
    }

    /**
     * Gets the value of the swiftKodBankeDuznika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwiftKodBankeDuznika() {
        return swiftKodBankeDuznika;
    }

    /**
     * Sets the value of the swiftKodBankeDuznika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwiftKodBankeDuznika(String value) {
        this.swiftKodBankeDuznika = value;
    }

    /**
     * Gets the value of the obracunskiRacunBankeDuznika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObracunskiRacunBankeDuznika() {
        return obracunskiRacunBankeDuznika;
    }

    /**
     * Sets the value of the obracunskiRacunBankeDuznika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObracunskiRacunBankeDuznika(String value) {
        this.obracunskiRacunBankeDuznika = value;
    }

    /**
     * Gets the value of the swiftKodBankePoverioca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwiftKodBankePoverioca() {
        return swiftKodBankePoverioca;
    }

    /**
     * Sets the value of the swiftKodBankePoverioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwiftKodBankePoverioca(String value) {
        this.swiftKodBankePoverioca = value;
    }

    /**
     * Gets the value of the obracunskiRacunBankePoverioca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObracunskiRacunBankePoverioca() {
        return obracunskiRacunBankePoverioca;
    }

    /**
     * Sets the value of the obracunskiRacunBankePoverioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObracunskiRacunBankePoverioca(String value) {
        this.obracunskiRacunBankePoverioca = value;
    }

    /**
     * Gets the value of the ukupanIznos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanIznos() {
        return ukupanIznos;
    }

    /**
     * Sets the value of the ukupanIznos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanIznos(BigDecimal value) {
        this.ukupanIznos = value;
    }

    /**
     * Gets the value of the sifraValute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifraValute() {
        return sifraValute;
    }

    /**
     * Sets the value of the sifraValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifraValute(String value) {
        this.sifraValute = value;
    }

    /**
     * Gets the value of the datumValute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumValute() {
        return datumValute;
    }

    /**
     * Sets the value of the datumValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumValute(String value) {
        this.datumValute = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the pojedinacnoPlacanje property.
     * 
     * @return
     *     possible object is
     *     {@link ClearingMt102 .PojedinacnoPlacanje }
     *     
     */
    
   // public ClearingMt102 .PojedinacnoPlacanje getPojedinacnoPlacanje() {
   //     return pojedinacnoPlacanje;
  //  }

    /**
     * Sets the value of the pojedinacnoPlacanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearingMt102 .PojedinacnoPlacanje }
     *     
     */
 //   public void setPojedinacnoPlacanje(ClearingMt102 .PojedinacnoPlacanje value) {
 //       this.pojedinacnoPlacanje = value;
 //   }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="id_naloga_za_placanje">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="50"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="duznik_nalogodavac">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="svrha_placanja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="primalac-poverilac">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="datum_naloga">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{2}-[0-9]{2}-[0-9]{4}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="datum_valute_p">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{2}-[0-9]{2}-[0-9]{4}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="broj_racuna_duznika">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{3}-[0-9]{13}-[0-9]{2}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="model_zaduzenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;minInclusive value="10"/>
     *               &lt;maxInclusive value="99"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="poziv_na_broj_zaduzenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;totalDigits value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="broj_racuna_poverioca">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{3}-[0-9]{13}-[0-9]{2}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="model_odobrenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;minInclusive value="10"/>
     *               &lt;maxInclusive value="99"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="poziv_na_broj_odobrenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;totalDigits value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="iznos">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;fractionDigits value="2"/>
     *               &lt;totalDigits value="15"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="sifra_valute_p">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    /*
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idNalogaZaPlacanjeAndDuznikNalogodavacAndSvrhaPlacanja"
    })
    public static class PojedinacnoPlacanje {

        @XmlElementRefs({
            @XmlElementRef(name = "iznos", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "datum_valute_p", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "broj_racuna_duznika", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "datum_naloga", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "model_odobrenja", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "sifra_valute_p", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "primalac-poverilac", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "poziv_na_broj_odobrenja", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "id_naloga_za_placanje", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "model_zaduzenja", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "poziv_na_broj_zaduzenja", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "duznik_nalogodavac", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "broj_racuna_poverioca", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "svrha_placanja", namespace = "soap.app/clearing_mt102", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<? extends Serializable>> idNalogaZaPlacanjeAndDuznikNalogodavacAndSvrhaPlacanja;

      
        public List<JAXBElement<? extends Serializable>> getIdNalogaZaPlacanjeAndDuznikNalogodavacAndSvrhaPlacanja() {
            if (idNalogaZaPlacanjeAndDuznikNalogodavacAndSvrhaPlacanja == null) {
                idNalogaZaPlacanjeAndDuznikNalogodavacAndSvrhaPlacanja = new ArrayList<JAXBElement<? extends Serializable>>();
            }
            return this.idNalogaZaPlacanjeAndDuznikNalogodavacAndSvrhaPlacanja;
        }

    }
    */
    
    
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idNalogaZaPlacanjeAndDuznikNalogodavacAndSvrhaPlacanja"
    })
    @Entity
    @Table(name="pojedinacno_placanje")
    public static class PojedinacnoPlacanje {
    	@Id
        @Column
    	@XmlElement(name = "id_naloga_za_placanje", required = true)
        protected String id_naloga_za_placanje;
    	@Column
        @XmlElement(name = "duznik-nalogodavac", required = true)
        protected String duznikNalogodavac;
    	@Column
        @XmlElement(name = "svrha_placanja", required = true)
        protected String svrhaPlacanja;
    	@Column
        @XmlElement(name = "primalac-poverilac", required = true)
        protected String primalacPoverilac;
    	@Column
        @XmlElement(required = true, defaultValue = "00-00-0000")
        protected String datum_naloga;
    	@Column
        @XmlElement(name = "oznaka_valute", required = true)
        protected String oznakaValute;
    	@Column
        @XmlElement(required = true)
        protected BigDecimal iznos;
    	@Column
        @XmlElement(name = "broj_racuna_duznika", required = true, defaultValue = "000-0000000000000-00")
        protected String brojRacunaDuznika;
    	@Column
        @XmlElement(name = "model_zaduzenja")
        protected int modelZaduzenja;
    	@Column
        @XmlElement(name = "poziv_na_broj_zaduzenja")
        protected int pozivNaBrojZaduzenja;
    	@Column
        @XmlElement(name = "broj_racuna_poverioca", required = true, defaultValue = "000-0000000000000-00")
        protected String brojRacunaPoverioca;
    	@Column
        @XmlElement(name = "model_odobrenja")
        protected int modelOdobrenja;
    	@Column
        @XmlElement(name = "poziv_na_broj_odobrenja")
        protected int pozivNaBrojOdobrenja;
    	@Column
        @XmlElement(required = true, defaultValue = "00-00-0000")
        protected String datum_valute;
    	
    	
    //	@OneToMany(mappedBy = "clearing_mt102")
    	@ManyToOne(cascade = CascadeType.ALL)
    	@JoinColumn(name= "maticni_clearing_id", referencedColumnName = "idPoruke")
    	 private ClearingMt102 matClearing;  
    	
        public ClearingMt102 getMatClearing() {
			return matClearing;
		}

		public void setMatClearing(ClearingMt102 matClearing) {
			this.matClearing = matClearing;
		}

		/**
         * Gets the value of the idPoruke property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdNalogaZaPlacanje() {
            return id_naloga_za_placanje;
        }

        /**
         * Sets the value of the idPoruke property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdNalogaZaPlacanje(String value) {
            this.id_naloga_za_placanje = value;
        }

        /**
         * Gets the value of the duznikNalogodavac property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDuznikNalogodavac() {
            return duznikNalogodavac;
        }

        /**
         * Sets the value of the duznikNalogodavac property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDuznikNalogodavac(String value) {
            this.duznikNalogodavac = value;
        }

        /**
         * Gets the value of the svrhaPlacanja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSvrhaPlacanja() {
            return svrhaPlacanja;
        }

        /**
         * Sets the value of the svrhaPlacanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSvrhaPlacanja(String value) {
            this.svrhaPlacanja = value;
        }

        /**
         * Gets the value of the primalacPoverilac property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimalacPoverilac() {
            return primalacPoverilac;
        }

        /**
         * Sets the value of the primalacPoverilac property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimalacPoverilac(String value) {
            this.primalacPoverilac = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatumNaloga() {
            return datum_naloga;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumNaloga(String value) {
            this.datum_naloga = value;
        }

        /**
         * Gets the value of the oznakaValute property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOznakaValute() {
            return oznakaValute;
        }

        /**
         * Sets the value of the oznakaValute property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOznakaValute(String value) {
            this.oznakaValute = value;
        }

        /**
         * Gets the value of the iznos property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getIznos() {
            return iznos;
        }

        /**
         * Sets the value of the iznos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setIznos(BigDecimal value) {
            this.iznos = value;
        }

        /**
         * Gets the value of the brojRacunaDuznika property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojRacunaDuznika() {
            return brojRacunaDuznika;
        }

        /**
         * Sets the value of the brojRacunaDuznika property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojRacunaDuznika(String value) {
            this.brojRacunaDuznika = value;
        }

        /**
         * Gets the value of the modelZaduzenja property.
         * 
         */
        public int getModelZaduzenja() {
            return modelZaduzenja;
        }

        /**
         * Sets the value of the modelZaduzenja property.
         * 
         */
        public void setModelZaduzenja(int value) {
            this.modelZaduzenja = value;
        }

        /**
         * Gets the value of the pozivNaBrojZaduzenja property.
         * 
         */
        public int getPozivNaBrojZaduzenja() {
            return pozivNaBrojZaduzenja;
        }

        /**
         * Sets the value of the pozivNaBrojZaduzenja property.
         * 
         */
        public void setPozivNaBrojZaduzenja(int value) {
            this.pozivNaBrojZaduzenja = value;
        }

        /**
         * Gets the value of the brojRacunaPoverioca property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojRacunaPoverioca() {
            return brojRacunaPoverioca;
        }

        /**
         * Sets the value of the brojRacunaPoverioca property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojRacunaPoverioca(String value) {
            this.brojRacunaPoverioca = value;
        }

        /**
         * Gets the value of the modelOdobrenja property.
         * 
         */
        public int getModelOdobrenja() {
            return modelOdobrenja;
        }

        /**
         * Sets the value of the modelOdobrenja property.
         * 
         */
        public void setModelOdobrenja(int value) {
            this.modelOdobrenja = value;
        }

        /**
         * Gets the value of the pozivNaBrojOdobrenja property.
         * 
         */
        public int getPozivNaBrojOdobrenja() {
            return pozivNaBrojOdobrenja;
        }

        /**
         * Sets the value of the pozivNaBrojOdobrenja property.
         * 
         */
        public void setPozivNaBrojOdobrenja(int value) {
            this.pozivNaBrojOdobrenja = value;
        }
    	
        public String getDatumValute() {
            return datum_valute;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumValute(String value) {
            this.datum_valute = value;
        }
    	
    }
}