//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 11:46:05 PM CEST 
//


package app.soap.clearing_mt102;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the app.soap.clearing_mt102 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClearingMt102PojedinacnoPlacanjeDatumNaloga_QNAME = new QName("soap.app/clearing_mt102", "datum_naloga");
    private final static QName _ClearingMt102PojedinacnoPlacanjeModelOdobrenja_QNAME = new QName("soap.app/clearing_mt102", "model_odobrenja");
    private final static QName _ClearingMt102PojedinacnoPlacanjeModelZaduzenja_QNAME = new QName("soap.app/clearing_mt102", "model_zaduzenja");
    private final static QName _ClearingMt102PojedinacnoPlacanjeIznos_QNAME = new QName("soap.app/clearing_mt102", "iznos");
    private final static QName _ClearingMt102PojedinacnoPlacanjeBrojRacunaPoverioca_QNAME = new QName("soap.app/clearing_mt102", "broj_racuna_poverioca");
    private final static QName _ClearingMt102PojedinacnoPlacanjeDuznikNalogodavac_QNAME = new QName("soap.app/clearing_mt102", "duznik_nalogodavac");
    private final static QName _ClearingMt102PojedinacnoPlacanjeIdNalogaZaPlacanje_QNAME = new QName("soap.app/clearing_mt102", "id_naloga_za_placanje");
    private final static QName _ClearingMt102PojedinacnoPlacanjePozivNaBrojOdobrenja_QNAME = new QName("soap.app/clearing_mt102", "poziv_na_broj_odobrenja");
    private final static QName _ClearingMt102PojedinacnoPlacanjeSifraValuteP_QNAME = new QName("soap.app/clearing_mt102", "sifra_valute_p");
    private final static QName _ClearingMt102PojedinacnoPlacanjeBrojRacunaDuznika_QNAME = new QName("soap.app/clearing_mt102", "broj_racuna_duznika");
    private final static QName _ClearingMt102PojedinacnoPlacanjePrimalacPoverilac_QNAME = new QName("soap.app/clearing_mt102", "primalac-poverilac");
    private final static QName _ClearingMt102PojedinacnoPlacanjeSvrhaPlacanja_QNAME = new QName("soap.app/clearing_mt102", "svrha_placanja");
    private final static QName _ClearingMt102PojedinacnoPlacanjeDatumValuteP_QNAME = new QName("soap.app/clearing_mt102", "datum_valute_p");
    private final static QName _ClearingMt102PojedinacnoPlacanjePozivNaBrojZaduzenja_QNAME = new QName("soap.app/clearing_mt102", "poziv_na_broj_zaduzenja");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: app.soap.clearing_mt102
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClearingMt102 }
     * 
     */
    public ClearingMt102 createClearingMt102() {
        return new ClearingMt102();
    }

    /**
     * Create an instance of {@link CreateClearingNalogRequest }
     * 
     */
    public CreateClearingNalogRequest createCreateClearingNalogRequest() {
        return new CreateClearingNalogRequest();
    }

    /**
     * Create an instance of {@link GetClearingNalogResponse }
     * 
     */
    public GetClearingNalogResponse createGetClearingNalogResponse() {
        return new GetClearingNalogResponse();
    }

    /**
     * Create an instance of {@link GetClearingNalogRequest }
     * 
     */
    public GetClearingNalogRequest createGetClearingNalogRequest() {
        return new GetClearingNalogRequest();
    }

    /**
     * Create an instance of {@link ClearingMt102 .PojedinacnoPlacanje }
     * 
     */
    public ClearingMt102 .PojedinacnoPlacanje createClearingMt102PojedinacnoPlacanje() {
        return new ClearingMt102 .PojedinacnoPlacanje();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "datum_naloga", scope = ClearingMt102 .PojedinacnoPlacanje.class, defaultValue = "00-00-0000")
    public JAXBElement<String> createClearingMt102PojedinacnoPlacanjeDatumNaloga(String value) {
        return new JAXBElement<String>(_ClearingMt102PojedinacnoPlacanjeDatumNaloga_QNAME, String.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "model_odobrenja", scope = ClearingMt102 .PojedinacnoPlacanje.class)
    public JAXBElement<Integer> createClearingMt102PojedinacnoPlacanjeModelOdobrenja(Integer value) {
        return new JAXBElement<Integer>(_ClearingMt102PojedinacnoPlacanjeModelOdobrenja_QNAME, Integer.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "model_zaduzenja", scope = ClearingMt102 .PojedinacnoPlacanje.class)
    public JAXBElement<Integer> createClearingMt102PojedinacnoPlacanjeModelZaduzenja(Integer value) {
        return new JAXBElement<Integer>(_ClearingMt102PojedinacnoPlacanjeModelZaduzenja_QNAME, Integer.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "iznos", scope = ClearingMt102 .PojedinacnoPlacanje.class)
    public JAXBElement<BigDecimal> createClearingMt102PojedinacnoPlacanjeIznos(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ClearingMt102PojedinacnoPlacanjeIznos_QNAME, BigDecimal.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "broj_racuna_poverioca", scope = ClearingMt102 .PojedinacnoPlacanje.class, defaultValue = "000-0000000000000-00")
    public JAXBElement<String> createClearingMt102PojedinacnoPlacanjeBrojRacunaPoverioca(String value) {
        return new JAXBElement<String>(_ClearingMt102PojedinacnoPlacanjeBrojRacunaPoverioca_QNAME, String.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "duznik_nalogodavac", scope = ClearingMt102 .PojedinacnoPlacanje.class)
    public JAXBElement<String> createClearingMt102PojedinacnoPlacanjeDuznikNalogodavac(String value) {
        return new JAXBElement<String>(_ClearingMt102PojedinacnoPlacanjeDuznikNalogodavac_QNAME, String.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "id_naloga_za_placanje", scope = ClearingMt102 .PojedinacnoPlacanje.class)
    public JAXBElement<String> createClearingMt102PojedinacnoPlacanjeIdNalogaZaPlacanje(String value) {
        return new JAXBElement<String>(_ClearingMt102PojedinacnoPlacanjeIdNalogaZaPlacanje_QNAME, String.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "poziv_na_broj_odobrenja", scope = ClearingMt102 .PojedinacnoPlacanje.class)
    public JAXBElement<Integer> createClearingMt102PojedinacnoPlacanjePozivNaBrojOdobrenja(Integer value) {
        return new JAXBElement<Integer>(_ClearingMt102PojedinacnoPlacanjePozivNaBrojOdobrenja_QNAME, Integer.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "sifra_valute_p", scope = ClearingMt102 .PojedinacnoPlacanje.class)
    public JAXBElement<String> createClearingMt102PojedinacnoPlacanjeSifraValuteP(String value) {
        return new JAXBElement<String>(_ClearingMt102PojedinacnoPlacanjeSifraValuteP_QNAME, String.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "broj_racuna_duznika", scope = ClearingMt102 .PojedinacnoPlacanje.class, defaultValue = "000-0000000000000-00")
    public JAXBElement<String> createClearingMt102PojedinacnoPlacanjeBrojRacunaDuznika(String value) {
        return new JAXBElement<String>(_ClearingMt102PojedinacnoPlacanjeBrojRacunaDuznika_QNAME, String.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "primalac-poverilac", scope = ClearingMt102 .PojedinacnoPlacanje.class)
    public JAXBElement<String> createClearingMt102PojedinacnoPlacanjePrimalacPoverilac(String value) {
        return new JAXBElement<String>(_ClearingMt102PojedinacnoPlacanjePrimalacPoverilac_QNAME, String.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "svrha_placanja", scope = ClearingMt102 .PojedinacnoPlacanje.class)
    public JAXBElement<String> createClearingMt102PojedinacnoPlacanjeSvrhaPlacanja(String value) {
        return new JAXBElement<String>(_ClearingMt102PojedinacnoPlacanjeSvrhaPlacanja_QNAME, String.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "datum_valute_p", scope = ClearingMt102 .PojedinacnoPlacanje.class, defaultValue = "00-00-0000")
    public JAXBElement<String> createClearingMt102PojedinacnoPlacanjeDatumValuteP(String value) {
        return new JAXBElement<String>(_ClearingMt102PojedinacnoPlacanjeDatumValuteP_QNAME, String.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/clearing_mt102", name = "poziv_na_broj_zaduzenja", scope = ClearingMt102 .PojedinacnoPlacanje.class)
    public JAXBElement<Integer> createClearingMt102PojedinacnoPlacanjePozivNaBrojZaduzenja(Integer value) {
        return new JAXBElement<Integer>(_ClearingMt102PojedinacnoPlacanjePozivNaBrojZaduzenja_QNAME, Integer.class, ClearingMt102 .PojedinacnoPlacanje.class, value);
    }

}
