//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 11:46:05 PM CEST 
// Generated on: 2017.06.13 at 09:51:16 PM CEST 
//


package app.soap.nalog_za_placanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nalog_za_placanje" type="{soap.app/nalog_za_placanje}nalog_za_placanje"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nalogZaPlacanje"
})
@XmlRootElement(name = "getNalogResponse")
public class GetNalogResponse {

    @XmlElement(name = "nalog_za_placanje", required = true)
    protected NalogZaPlacanje nalogZaPlacanje;

    /**
     * Gets the value of the nalogZaPlacanje property.
     * 
     * @return
     *     possible object is
     *     {@link NalogZaPlacanje }
     *     
     */
    public NalogZaPlacanje getNalogZaPlacanje() {
        return nalogZaPlacanje;
    }

    /**
     * Sets the value of the nalogZaPlacanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link NalogZaPlacanje }
     *     
     */
    public void setNalogZaPlacanje(NalogZaPlacanje value) {
        this.nalogZaPlacanje = value;
    }

}
