//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 11:46:05 PM CEST 
//


package app.soap.nalog_za_placanje;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the app.soap.nalog_za_placanje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Date_QNAME = new QName("soap.app/nalog_za_placanje", "date");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: app.soap.nalog_za_placanje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetNalogRequest }
     * 
     */
    public GetNalogRequest createGetNalogRequest() {
        return new GetNalogRequest();
    }

    /**
     * Create an instance of {@link GetNalogResponse }
     * 
     */
    public GetNalogResponse createGetNalogResponse() {
        return new GetNalogResponse();
    }

    /**
     * Create an instance of {@link NalogZaPlacanje }
     * 
     */
    public NalogZaPlacanje createNalogZaPlacanje() {
        return new NalogZaPlacanje();
    }

    /**
     * Create an instance of {@link CreateNalogRequest }
     * 
     */
    public CreateNalogRequest createCreateNalogRequest() {
        return new CreateNalogRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "soap.app/nalog_za_placanje", name = "date", defaultValue = "00-00-0000")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

}
